// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPFT60-APk03XWdvs0AVL1kfL9YblblTM',
    appId: '1:651893550080:web:5b151368cdbcb2c3b1fce5',
    messagingSenderId: '651893550080',
    projectId: 'beverage-ims',
    authDomain: 'beverage-ims.firebaseapp.com',
    storageBucket: 'beverage-ims.firebasestorage.app',
    measurementId: 'G-G0FNJLH52F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLSjyi6FWgeoj91kn8Gap-wZgAFt9dilM',
    appId: '1:651893550080:android:141cfd44ea61de7ab1fce5',
    messagingSenderId: '651893550080',
    projectId: 'beverage-ims',
    storageBucket: 'beverage-ims.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEE3JUVUHYv7flQXdynW1gZ5ku2e_aQTc',
    appId: '1:651893550080:ios:dce7075539c35163b1fce5',
    messagingSenderId: '651893550080',
    projectId: 'beverage-ims',
    storageBucket: 'beverage-ims.firebasestorage.app',
    iosBundleId: 'com.example.beverageIms',
  );
}
